name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Setup pnpm
      - name: Enable corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@10 --activate

      # Install deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Create .env from GitHub Secrets
      - name: Create .env file
        run: |
          echo "NODE_ENV=prod" >> .env
          echo "DEBUG_CONSOLE=${{ secrets.DEBUG_CONSOLE }}" >> .env
          echo "DEBUG_FILE=${{ secrets.DEBUG_FILE }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "TELE_CHAT_ID=${{ secrets.TELE_CHAT_ID }}" >> .env
          echo "TELE_BOT_TOKEN=${{ secrets.TELE_BOT_TOKEN }}" >> .env

      # (optional) Debug
      - name: Check .env exists
        run: ls -la .env

      # Build
      - name: Run build
        run: pnpm run build

      # Prisma Generate
      - name: Run prisma:generate
        run: pnpm run prisma:generate

      # Cleanup
      - name: Remove folder and file for optimize
        run: |
          rm -rf \
            types \
            src \
            tsconfig.json \
            Dockerfile \
            .dockerignore \
            .env.example \
            .github \
            .husky \
            .vscode

      # Deploy Vercel
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
